apiVersion: batch/v1
kind: CronJob
metadata:
  name: news-updater
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          containers:
            - name: news-updater
              image: hnnynh/paperple-crawling:latest # private
          restartPolicy: OnFailure
