 pipeline {
    agent any

    environment {
        REPO = 'lunch-12/PAPERPLE-AI'
        IMAGE_NAME = 'paperple-ai'
        ECR_ACCESS = 'ECR_Access'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: "https://github.com/${REPO}.git"
            }
        }
        
        stage('Remove Previous Docker Image') {
            steps {
                script {
                    def images = sh(script: "docker images -q '${IMAGE_NAME}'", returnStdout: true).trim()

                    if (images) {
                        sh "docker rmi -f ${images} || true"
                        echo "Deleted Docker images: ${images}"
                    } else {
                        echo "No Docker images found with name: ${IMAGE_NAME}"
                    }
                }
            }
        }
            
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${IMAGE_NAME}:v0.0.${env.BUILD_NUMBER}")
                }
            }
        }
        
        stage('Run Container and Health Check') {
            steps {
                script {
                    sh "docker run -d --name run-test -p 8000:8000 ${IMAGE_NAME}:v0.0.${env.BUILD_NUMBER}"
                    sleep(10)
                    
                    def httpCode = sh(script: 'curl -s -o /dev/null -w %{http_code} http://localhost:8000/health', returnStdout: true).trim()
                    
                    if(httpCode != '200')
                        error("Health Check Failure: ${httpCode}")
                }
            }
        }
 
        stage('Test Env Cleanup') {
            steps {
                script {
                    sh 'docker stop run-test'
                    sh 'docker rm run-test'
                }
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry("https://024848437933.dkr.ecr.ap-northeast-2.amazonaws.com", "ecr:ap-northeast-2:${env.ECR_ACCESS}") {
                        docker.image("${env.IMAGE_NAME}:v0.0.${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }
        
        stage('Trigger CD Job') {
            steps {
                echo "IMAGE_TAG = v0.0.${env.BUILD_NUMBER}"
                build job: 'paperple-ai-cd', parameters: [string(name: 'IMAGE_TAG', value: "v0.0.${env.BUILD_NUMBER}")], 
                    wait: false
            }
        }

    }
    post {
        success {
            slackSend (
                channel: '#클라우드', 
                color: '#00FF00', 
                message: "BUILD SUCCESS: ${REPO} BUILD Job ${env.JOB_NAME} [${env.BUILD_NUMBER}]"
            )
        }
        failure {
            slackSend (
                channel: '#클라우드', 
                color: '#FF0000', 
                message: "BUILD FAIL: ${REPO} BUILD Job ${env.JOB_NAME} [${env.BUILD_NUMBER}]"
            )
        }
    }
}